apiVersion: v2
name: csi-driver-nfs
description: Deploys csi-driver-nfs
version: 0.1.0
dependencies:
  - name: csi-driver-nfs
    version: v4.8.0
    repository: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
