{{- range .Values.storage_classes -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .name }}
provisioner: rancher.io/local-path
reclaimPolicy: {{ .reclaimPolicy }}
volumeBindingMode: {{ default "WaitForFirstConsumer" .volumeBindingMode }}
parameters:
  nodePath: {{ .nodePath }}
---
{{ end }}
